# Danh sách các điểm với toạ độ (bao gồm vị trí và góc quay)
geometry_msgs/Pose[] points       # Danh sách các điểm bao gồm vị trí và góc quay

# Vận tốc giữa các điểm
float64[] velocity                # Vận tốc giữa các điểm

# Hoạt động trên các điểm
int32[] point_activity            # Hoạt động trên các điểm

# Hoạt động trên các cạnh nối giữa các điểm
int32[] edge_activity             # Hoạt động trên các đường nối